### ISSUE TITLE
compilation error in windows

### ISSUE THREAD

**Issue by gdidomenico** [medicalphysics/DXMClib#1]
The compilation using visual C++ 2017 fails. 
The error is  
DXMClib\include\dxmc/floating.hpp(25): error C2061: sintax error: unknown identifier 'Floating'

It seems the keyword concept is unknown in floating.hpp

#include <type_traits>

namespace dxmc {
template <typename T>
concept Floating = std::is_floating_point<T>::value;
}

**Comment by medicalphysics** [comment]
Hi,
Could you post the complete error message?
Thanks, Erlend

**Comment by gdidomenico** [comment]
the complete error message is:

Error	C2061	syntax error: identifier 'Floating'	libdxmc	D:\Reconstruction\DXMClib\include\dxmc\floating.hpp	25	
Error	C2989	'std::align_val_t': class template has already been declared as a non-class template	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	43	
Error	C3433	'align_val_t': all declarations of an enumeration must have the same underlying type, was 'unsigned __int64' now 'int'	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	43	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	74	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	73	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	85	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	84	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	94	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	93	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	103	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	102	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	127	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	126	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	141	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	140	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	152	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	151	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	163	
Error	C2955	'std::nothrow_t': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h	162	
Error	C2143	syntax error: missing ';' before 'identifier'	libdxmc	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\crtdbg.h	123	
Error	C2039	'int8_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	18	
Error	C2873	'int8_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	18	
Error	C2039	'int16_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	18	
Error	C2873	'int16_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	18	
Error	C2039	'int32_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	19	
Error	C2873	'int32_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	19	
Error	C2039	'int64_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	19	
Error	C2873	'int64_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	19	
Error	C2039	'uint8_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	20	
Error	C2873	'uint8_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	20	
Error	C2039	'uint16_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	20	
Error	C2873	'uint16_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	20	
Error	C2039	'uint32_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	21	
Error	C2873	'uint32_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	21	
Error	C2039	'uint64_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	21	
Error	C2873	'uint64_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	21	
Error	C2039	'int_least8_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	23	
Error	C2873	'int_least8_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	23	
Error	C2039	'int_least16_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	23	
Error	C2873	'int_least16_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	23	
Error	C2039	'int_least32_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	24	
Error	C2873	'int_least32_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	24	
Error	C2039	'int_least64_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	24	
Error	C2873	'int_least64_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	24	
Error	C2039	'uint_least8_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	25	
Error	C2873	'uint_least8_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	25	
Error	C2039	'uint_least16_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	25	
Error	C2873	'uint_least16_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	25	
Error	C2039	'uint_least32_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	26	
Error	C2873	'uint_least32_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	26	
Error	C2039	'uint_least64_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	26	
Error	C2873	'uint_least64_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	26	
Error	C2039	'int_fast8_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	28	
Error	C2873	'int_fast8_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	28	
Error	C2039	'int_fast16_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	28	
Error	C2873	'int_fast16_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	28	
Error	C2039	'int_fast32_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	29	
Error	C2873	'int_fast32_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	29	
Error	C2039	'int_fast64_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	29	
Error	C2873	'int_fast64_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	29	
Error	C2039	'uint_fast8_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	30	
Error	C2873	'uint_fast8_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	30	
Error	C2039	'uint_fast16_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	30	
Error	C2873	'uint_fast16_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	30	
Error	C2039	'uint_fast32_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	31	
Error	C2873	'uint_fast32_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	31	
Error	C2039	'uint_fast64_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	31	
Error	C2873	'uint_fast64_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	31	
Error	C2039	'intmax_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	33	
Error	C2873	'intmax_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	33	
Error	C2039	'uintmax_t': is not a member of '`global namespace''	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	34	
Error	C2873	'uintmax_t': symbol cannot be used in a using-declaration	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cstdint	34	
Error	C2143	syntax error: missing ';' before 'identifier'	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ymath.h	41	
Error	C2332	'union': missing tag name	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ymath.h	41	
Error	C3306	'<anonymous-tag>': unnamed class template is not allowed	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ymath.h	41	
Error	C2646	an anonymous union at global or namespace scope must be declared static	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ymath.h	41	
Error	C2146	syntax error: missing ';' before identifier '_Denorm'	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ymath.h	49	
Error	C2146	syntax error: missing ';' before identifier '_FDenorm'	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ymath.h	58	
Error	C2146	syntax error: missing ';' before identifier '_LDenorm'	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ymath.h	66	
Error	C2440	'initializing': cannot convert from 'initializer list' to 'std::align_val_t'	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xmemory0	58	
Error	C2955	'std::_Lockit': use of class template requires template argument list	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xlocinfo	225	
Error	C2079	'std::_Locinfo::_Lock' uses undefined class 'std::_Lockit'	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xlocinfo	225	
Error	C1903	unable to recover from previous error(s); stopping compilation	libdxmc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xlocinfo	76

**Comment by medicalphysics** [comment]
Thanks, dxmclib requires support for concepts and std::atomic_ref which is supported by MSVC since version 16.8. It appears that you are on version 14.16. Is it possible for you to try a later version? 
-Erlend
